"""Render a CatalogResult to CATALOG.md, STALENESS.md, and catalog.json.

CATALOG.md / STALENESS.md keep the section structure (and STALENESS's line-3
summary phrasing) of the original kb_index.py output, so existing hooks and
docs that reference them keep working. catalog.json is the machine surface —
`status`, `search`, and agent hooks consume it instead of parsing markdown.
"""

from __future__ import annotations

import json

from .catalog import CatalogResult
from .config import Config

GENERATED = "generated by `librarian index`. DO NOT EDIT BY HAND."


def catalog_md(cfg: Config, res: CatalogResult) -> str:
    by_domain = res.by_domain()
    lines = [
        f"# CATALOG — {GENERATED}",
        "",
        f"{len(res.items)} entries ({res.n_docs} docs + {res.n_artifacts} artifacts) across "
        f"{len(by_domain)} domains · {len(res.missing_fm)} md need frontmatter · "
        f"{len(res.uncovered)} code/data need a registry entry · {len(res.stale)} flagged. "
        f"Find via `domain` + `read_when` + grep.",
        "",
    ]
    for dom in sorted(by_domain):
        lines += [
            f"## {dom}",
            "| id | title | kind | status | last_verified | path |",
            "|----|-------|------|--------|---------------|------|",
        ]
        for d in sorted(by_domain[dom], key=lambda x: (x["kind"] != "doc", str(x.get("id", x["_path"])))):
            lines.append(
                f"| {d.get('id', '?')} | {d.get('title', '?')} | {d.get('kind', '?')} | "
                f"{d.get('status', '?')} | {d.get('last_verified', '-')} | `{d['_path']}` |"
            )
        lines.append("")
    if res.missing_fm:
        lines += ["## Backlog — .md missing frontmatter", ""]
        lines += [f"- `{p}`" for p in res.missing_fm] + [""]
    if res.uncovered:
        lines += [f"## Backlog — code/data with no registry entry (add to {cfg.artifacts_file})", ""]
        lines += [f"- `{p}`" for p in sorted(res.uncovered)] + [""]
    if res.unverified:
        lines += [
            "## Unverified-tier sources (authority=unverified — claims are CONTEXT, not fact; "
            "verify before trusting; a conflict with a verified fact loses)",
            "",
        ]
        lines += [
            f"- `{d['_path']}` ({d.get('title', '?')})"
            for d in sorted(res.unverified, key=lambda x: x["_path"])
        ] + [""]
    return "\n".join(lines).rstrip("\n") + "\n"


def staleness_md(cfg: Config, res: CatalogResult) -> str:
    # Line 3 is the legacy summary line — keep its phrase patterns stable; shell
    # hooks in pre-librarian installs grep it.
    lines = [
        f"# STALENESS — {GENERATED}",
        "",
        f"{len(res.inbox_pending)} awaiting intake ({cfg.inbox_dir}) · {len(res.stale)} flagged · "
        f"{len(res.orphans)} orphaned · {len(res.conflicts)} OPEN conflicts "
        f"({len(res.conflicts_ack)} acknowledged) · {len(res.missing_fm)} md need frontmatter · "
        f"{len(res.uncovered)} code/data unregistered. Run `librarian verify` for facts-vs-live.",
        "",
        "_Resolve a conflict by: (1) FIXING the doc (correct/remove the line + drop the marker) — the "
        "repo is the source of truth, so this is preferred; (2) ACKNOWLEDGING it (mark the disputed line "
        "as reviewed if it's intentionally kept); or (3) ARCHIVING the whole doc to "
        f"`{cfg.archive_dir}/` (drops out of the catalog)._",
        "",
    ]
    if res.registry_errors:
        lines += ["## Registry errors (entries skipped — fix these first)", ""]
        lines += [f"- {e}" for e in res.registry_errors] + [""]
    if res.inbox_pending:
        lines += [
            "## Inbox — raw docs awaiting intake (triage -> tier -> conflict-check -> frontmatter -> file)",
            "",
        ]
        lines += [f"- `{cfg.inbox_dir}/{f}`" for f in res.inbox_pending] + [""]
    if res.conflicts:
        lines += [
            "## OPEN conflicts (disputed claims — false-now; FIX the doc, ACKNOWLEDGE to keep, or archive)",
            "",
            "| doc | line | text |",
            "|-----|------|------|",
        ]
        lines += [f"| `{p}` | {i} | {t} |" for (p, i, t) in sorted(res.conflicts)] + [""]
    if res.conflicts_ack:
        lines += [
            f"_{len(res.conflicts_ack)} acknowledged conflict(s) — reviewed + intentionally kept._",
            "",
        ]
    if res.orphans:
        lines += ["## Orphaned registry entries (file missing — fix path or drop entry)", ""]
        lines += [f"- {i} -> `{p}`" for (i, p) in sorted(res.orphans)] + [""]
    if res.stale:
        lines += [
            "## Flagged (provisional/draft/overdue/disputed/missing-fields)",
            "",
            "| id | path | why |",
            "|----|------|-----|",
        ]
        lines += [f"| {i} | `{p}` | {w} |" for (i, p, w) in sorted(res.stale)] + [""]
    if res.fm_warnings:
        lines += [
            "## Frontmatter warnings (fields the parser could not read — fix the YAML)",
            "",
            "| doc | warning |",
            "|-----|---------|",
        ]
        lines += [f"| `{p}` | {w} |" for (p, w) in sorted(res.fm_warnings)] + [""]
    if res.absence_claims:
        lines += [
            "## Absence-claims (ADVISORY — sanity-check, not errors)",
            "",
            '_A confidently-stated gap ("not identified", "TBD", "we don\'t have X") can be '
            "wrong if the catalog already fills it elsewhere. Most hits are legitimate (a real "
            "TODO/known gap); the point is to eyeball each: does X already exist in the catalog? "
            "Verify positively before trusting._",
            "",
            "| doc | line | text |",
            "|-----|------|------|",
        ]
        lines += [f"| `{p}` | {i} | {t} |" for (p, i, t) in sorted(res.absence_claims)] + [""]
    if res.coverage_gaps:
        lines += [
            "## Correctness coverage (ADVISORY — checkable facts with no verify check)",
            "",
            "_These docs assert a number/count/ID but have no `[[verify.checks]]` entry guarding it, so it "
            "can silently drift from its source. Not every hit warrants a check — the point is the missing "
            "check is visible. `/librarian-dream` can draft the check for you._",
            "",
            "| id | doc | claim |",
            "|----|-----|-------|",
        ]
        lines += [f"| {i} | `{p}` | {t} |" for (i, p, t) in sorted(res.coverage_gaps)] + [""]
    if not (res.orphans or res.stale or res.conflicts):
        lines.append(
            "Nothing flagged." + (" (See advisory absence-claims above.)" if res.absence_claims else "")
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def catalog_json(res: CatalogResult) -> str:
    entries = []
    for d in sorted(res.items, key=lambda x: x["_path"]):
        e = {k: v for k, v in d.items() if not k.startswith("_")}
        e["path"] = d["_path"]
        entries.append(e)
    payload = {
        "schema_version": 1,
        "summary": res.summary(),
        "entries": entries,
        "flags": {
            "missing_frontmatter": res.missing_fm,
            "frontmatter_warnings": [{"path": p, "warning": w} for p, w in sorted(res.fm_warnings)],
            "stale": [{"id": i, "path": p, "why": w} for i, p, w in sorted(res.stale)],
            "orphans": [{"id": i, "path": p} for i, p in sorted(res.orphans)],
            "open_conflicts": [{"path": p, "line": i, "text": t} for p, i, t in sorted(res.conflicts)],
            "acknowledged_conflicts": [
                {"path": p, "line": i, "text": t} for p, i, t in sorted(res.conflicts_ack)
            ],
            "absence_claims": [{"path": p, "line": i, "text": t} for p, i, t in sorted(res.absence_claims)],
            "coverage_gaps": [{"id": i, "path": p, "text": t} for i, p, t in sorted(res.coverage_gaps)],
            "unverified_sources": sorted(d["_path"] for d in res.unverified),
            "uncovered": sorted(res.uncovered),
            "inbox_pending": res.inbox_pending,
            "registry_errors": res.registry_errors,
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_all(cfg: Config, res: CatalogResult) -> None:
    out = cfg.path(cfg.index_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "CATALOG.md").write_text(catalog_md(cfg, res), encoding="utf-8")
    (out / "STALENESS.md").write_text(staleness_md(cfg, res), encoding="utf-8")
    (out / "catalog.json").write_text(catalog_json(res), encoding="utf-8")
